### ISSUE TITLE
Linked Attachments in Current Outfit Folder get treated as InventoryTexture and are subsequently removed on login

### ISSUE THREAD

**Issue by toxalph** [cinderblocks/libremetaverse#102]
Issue doesn't occur in version 2.0, looks related to recent changes in AppearanceManager, but not entirely sure.

Here's output from libomv:

10:08:06,757 [9] INFO  - <Hall Monitor>: 11 inventory items in 'Current Outfit' folder
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Head' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Left Forarm' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Legs' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Skin' found in 'Current Outfit' folder (InventoryWearable)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Right Forearm' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Right Upper Arm' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rhiannon - Eyes' found in 'Current Outfit' folder (InventoryWearable)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Hair' found in 'Current Outfit' folder (InventoryWearable)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Shape' found in 'Current Outfit' folder (InventoryWearable)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Left Upper Arm' found in 'Current Outfit' folder (InventoryTexture)
10:08:06,757 [9] INFO  - <Hall Monitor>: 'Rosie Body' found in 'Current Outfit' folder (InventoryTexture)

Each of the "InventoryTexture" items are actually links to prim attachments, subsequently they are dropped in RequestAgentWorn(), then SendOutfitToCurrentSimulator() does not include them and they are removed from the avatar - removing the last line "Client.Network.SendPacket(attachmentsPacket)" in SendOutfitToCurrentSimulator() fixes it, but obviously is not the solution. 

Here's a screenshot showing the inventory:

<img width="409" alt="Image" src="https://github.com/user-attachments/assets/9bb13733-48c8-4471-a415-f4776277a732" />

**Comment by toxalph** [comment]
Furthermore I used git bisect to track down the commit that introduces the issues: 092b5c8bb3ad548c62baf1e9db7b855bc50c9348

**Comment by cinderblocks** [comment]
Looks like actually introduced in f1d3534818f094bf63e88f84eb607b58678246f2 . Working on it. Easy enough to fix, we do it elsewhere, but I'd like to figure out why those are being interpreted as InventoryTexture in the first place.

**Comment by cinderblocks** [comment]
I believe this is fixed in v2.2.24 6425cf630b420655dd4a5e153a1e03aaf7b4f942 Please confirm.

**Comment by toxalph** [comment]
Unable to confirm sorry, I'm working within a (unmodified) clone of the repo rather than an official release - I've tried from latest commit as well as https://github.com/cinderblocks/libremetaverse/commit/6425cf630b420655dd4a5e153a1e03aaf7b4f942 but I still get the same output and failed outfit:

TestClient git:(master) ✗ git checkout 6425cf6
Note: switching to '6425cf6'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by switching back to a branch.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -c with the switch command. Example:

  git switch -c <new-branch-name>

Or undo this operation with:

  git switch -

Turn off this advice by setting config variable advice.detachedHead to false

HEAD is now at 6425cf63 Mesh can be attached, right? :/
(.env) ➜  TestClient git:(6425cf63) ✗ dotnet run --framework net8.0 --file=
13:54:26,111 [1] INFO  - No log configuration found, defaulting to console logging
13:54:26,128 [1] INFO  - Using login URI https://login.agni.lindenlab.com/cgi-bin/login.cgi
Type quit to exit.  Type help for a command list.
0 avatars online> 13:54:28,189 [8] DEBUG - <Hall Monitor>: Setting InventoryRoot to 8470cd5f-bfba-4d90-8f1e-b1bb01a6f04d
13:54:28,194 [8] DEBUG - <Hall Monitor>: Login status: ConnectingToSim: Connecting to simulator...
13:54:28,195 [8] INFO  - <Hall Monitor>: Login ConnectingToSim: Connecting to simulator...
13:54:28,201 [8] INFO  - <Hall Monitor>: Connecting to (34.214.150.191:13055)
13:54:28,904 [8] INFO  - <Hall Monitor>: Sending complete agent movement to 947779023497472 /
13:54:29,156 [8] DEBUG - <Hall Monitor>: Login status: Success: Honoring the Past, Embracing the Future: Your New Linden Home Awaits in Second Life! https://second.life/news050225
13:54:29,158 [8] INFO  - <Hall Monitor>: Login Success: Honoring the Past, Embracing the Future: Your New Linden Home Awaits in Second Life! https://second.life/news050225
13:54:29,159 [8] INFO  - Logged in Hall Monitor
13:54:30,192 [11] DEBUG - <Hall Monitor>: Starting event queue for Simulator (34.214.150.191:13055)
13:54:30,576 [8] INFO  - <Hall Monitor>: Requesting bake for COF version 69
13:54:30,776 [6] INFO  - <Hall Monitor>: Returning appearance information from server-side bake request.
13:54:31,160 [11] INFO  - <Hall Monitor>: 11 inventory items in 'Current Outfit' folder
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Head' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Left Forarm' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Legs' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Skin' found in 'Current Outfit' folder (InventoryWearable)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Right Forearm' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Right Upper Arm' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rhiannon - Eyes' found in 'Current Outfit' folder (InventoryWearable)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Hair' found in 'Current Outfit' folder (InventoryWearable)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Shape' found in 'Current Outfit' folder (InventoryWearable)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Left Upper Arm' found in 'Current Outfit' folder (InventoryTexture)
13:54:31,160 [11] INFO  - <Hall Monitor>: 'Rosie Body' found in 'Current Outfit' folder (InventoryTexture)

**Comment by cinderblocks** [comment]
It looks like objects that have been attached in-world prior to being stored on the asset server are stored with the InventoryType of 0 (Texture) instead of 17 (Attachment). Fix will be forthcoming with some more comprehensive inventory improvements.
